CREATE TABLE USERS (
    ID VARCHAR(255), 
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    ISACTIVE BOOLEAN,
    TOKEN VARCHAR(255),
    LASTLOGIN TIMESTAMP,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE PHONES (
    ID VARCHAR(255), 
    NUMBER VARCHAR(255),
    CITYCODE VARCHAR(255),
    COUNTRYCODE VARCHAR(255),
    CREATED TIMESTAMP,
    USERID VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (USERID) REFERENCES USERS(ID)
);